
#+options: ':t *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+options: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+options: email:nil f:t inline:nil num:t p:nil pri:nil prop:nil stat:t tags:t
#+options: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+title: Basic philosophical commitments
#+author: Avery Rose Randall
#+email: l.avery.randall@gmail.com
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+cite_export: natbib
#+latex_class: blank
#+latex_class_options:
#+latex_header:
#+latex_header_extra:
#+description:
#+keywords:
#+subtitle:
#+latex_engraved_theme:
#+date: \today

#+export_file_name: ../Chapters/Basic_philosophical_commitments
#+filetags: :autocompile:

* Basic philosophical commitments
  :PROPERTIES:
  :CUSTOM_ID: chap:basic-comm
  :END:
  :LOGBOOK:
  CLOCK: [2023-10-09 Mon 07:00]--[2023-10-09 Mon 07:25] =>  0:25
  :END:

  I want to start this essay by setting out some basic features of my approach to
  moral philosophy.
  One of the most important features of my approach is a form of pragmatic pluralism
  about both ontology and ethics.
  The gist of this position is that the world itself does not fully determine either
  a singular true portrayal of the world, or a single correct set of ethical
  beliefs.
  Human beings construct their understandings of the world and their ethical views
  through active engagement with the world.
  This process is shaped both by deep features of the world itself and by the
  culture, practices, aims, and history of the community and individuals that are
  seeking to understand the world or to make sound ethical judgments.
  Consequently, I think that different communities might come to understand the
  world, in very different ways, and nonetheless have views that reflect deep
  features of the world and serve the purposes for which they are seeking to
  understand the world.
  Likewise, I think that different communities or individuals might come to adopt
  very different sets of ethical beliefs and practices which all reflect deep
  ethical truths and all constitute sound ethical practice.
  This implies that there may be more than one correct, (or at least reasonable)
  understanding of the world, and that their may be more than one sound set of
  ethical beliefs and practices.
  It does not imply, however, that all beliefs about the world or all sets of
  ethical belief and practice are equally valid or reasonable.
  Some models of the world are more accurate or more useful than others, and some
  sets of ethical belief and practice are more consistent with deep ethical truths
  than others.

  I will explain these positions in more detail in the following sections.
  First I will explain the particular flavor of ontological pluralism that informs
  my ethics and metaethics in \refse{sec:ont_plural}.
  After this I will explain how I understand moral reasoning, in
  \refse{sec:nat_mor}. This will enable me to defend a form of ethical and
  metaethical pluralism in \refse{sec:eth_plur}.
  
  This actually sucks I don't think that it is at all a good version of org 
  mode to be editin

** Ontological pluralism
   :PROPERTIES:
   :ID:       0de577ff-be19-4e7e-892b-586fc8d4c349
   :CUSTOM_ID: sec:ont_plural
   :END:
   :LOGBOOK:
   CLOCK: [2023-10-10 Tue 06:56]--[2023-10-10 Tue 07:26] =>  0:30
   :END:

   There is no uniquely correct way to understand the world.
   When we seek to understand the world, we use concepts that we have inherited from
   others or we develop our own.
   These concepts give us ways to understand and interact with the world
   effectively.
   We use these concepts to model the world and to chop it into manageable bits that
   we can understand.
   So, for instance, when I look at the corner my desk, I do not simply see a series
   of meaningless shapes and colors; I see a colorful lamp and a pine cone that I
   put there to make my space feel warm and inviting.
   /Lamp/, /pine cone/, and /desk/ are useful concepts for me because they provide a
   meaningful way for me to model and interact with my world.
   It is useful to think of lamps, pine cones, and desks both as wholes and as
   distinct and persistent physical objects, because I interact with them as
   distinct and persistent physical objects.
   These concepts also constitute meaningful categories because they reflect
   important, recognizable patterns in my world (many trees in the pacific northwest
   produce seed-bearing cones), or they reflect ways in which people regularly
   interact with objects in my world (people make lamps and desks and use them to
   light their rooms or to write essays on).
   # These categories reflect both features of the objects themselves and ways that 
   # human beings tend to interact with them. 
   # It is useful to think of them as different types of physical objects because they
   # I can arrange them in my room and  elp me to make sense of my experience.
   # They are all generic concepts that allow me to categorize a variety of distinct,
   # but similar objects.
   # These categories help me to understand my world and interact with it effectively.
   # /Lamp/, /pine cone/, and /desk/ are useful concepts because they are all

   This suggests that the concepts that 

** On the nature of morality and moral reasoning
   :PROPERTIES:
   :CUSTOM_ID: sec:nat_mor
   :END:

** Ethical and metaethical pluralism
   :PROPERTIES:
   :CUSTOM_ID: sec:eth_plur
   :END:





   There are at least four basic philosophical commitments that inform my approach.

   I want to answer the question, what are we doing when we are doing moral
   philosophy.

* Foundational ethical commitments
  :PROPERTIES:
  :CUSTOM_ID: ch:eth_com
  :END:
