#+latex_class: blank
#+latex_class_options:
#+latex_header:
#+latex_header_extra:
#+description:
#+keywords:
#+subtitle:
#+latex_engraved_theme:
#+date: \today
#+filetags: :autocompile:
#+export_file_name: ~/Dropbox/Essays/Without_things/Chapters/Dignity_without_higher_and_lower

* Dignity without higher and lower?
:PROPERTIES:
:CUSTOM_ID: ch:dignity
:END:


Appeals to human dignity are both broadly appealing and rhetorically powerful.
Part of the reason that they are so broadly appealing is that the term /human
dignity/ can be imbued with a wide variety of meanings.
A person can claim that all human beings have dignity or claim that a particular
social arrangement or action is inconsistent with human dignity without
specifying precisely what they mean by /dignity/ or what gives human beings
dignity.
This does not mean that /human dignity/ has no meaning or that it can mean
whatever the speaker wants it to mean.
Rather, the term refers to a constellation of moral and ethical concepts.

When politicians and moral philosophers appeal to human dignity they can be
pointing to any of several ethical and political concepts that go by this name.


Human dignity, as an ethical and political concept or rather constellation of
concepts is both rich and evocative.

At the center of this idea, or perhaps constellation of ideas is the notion that
human beings are valuable or elevated in some way.
Proponents of the av It has a broad appeal in part because it is ambiguous and

Dignity is not a sterile idea, it demands more than a specific set of actions,
it demands reverence
